/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PaymentCancelRouteImport } from './routes/payment/cancel'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'
import { Route as HousesCreateRouteImport } from './routes/houses/create'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as HousesIdIndexRouteImport } from './routes/houses/$id/index'
import { Route as HousesIdInviteRouteImport } from './routes/houses/$id/invite'
import { Route as HousesIdExpensesNewRouteImport } from './routes/houses/$id/expenses/new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesCreateRoute = HousesCreateRouteImport.update({
  id: '/houses/create',
  path: '/houses/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIdIndexRoute = HousesIdIndexRouteImport.update({
  id: '/houses/$id/',
  path: '/houses/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIdInviteRoute = HousesIdInviteRouteImport.update({
  id: '/houses/$id/invite',
  path: '/houses/$id/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIdExpensesNewRoute = HousesIdExpensesNewRouteImport.update({
  id: '/houses/$id/expenses/new',
  path: '/houses/$id/expenses/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/houses/create': typeof HousesCreateRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/houses/$id/invite': typeof HousesIdInviteRoute
  '/houses/$id': typeof HousesIdIndexRoute
  '/houses/$id/expenses/new': typeof HousesIdExpensesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/houses/create': typeof HousesCreateRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/houses/$id/invite': typeof HousesIdInviteRoute
  '/houses/$id': typeof HousesIdIndexRoute
  '/houses/$id/expenses/new': typeof HousesIdExpensesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/houses/create': typeof HousesCreateRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/houses/$id/invite': typeof HousesIdInviteRoute
  '/houses/$id/': typeof HousesIdIndexRoute
  '/houses/$id/expenses/new': typeof HousesIdExpensesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agreement'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/auth/callback'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/houses/create'
    | '/invitations/accept'
    | '/payment/cancel'
    | '/payment/success'
    | '/houses/$id/invite'
    | '/houses/$id'
    | '/houses/$id/expenses/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agreement'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/auth/callback'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/houses/create'
    | '/invitations/accept'
    | '/payment/cancel'
    | '/payment/success'
    | '/houses/$id/invite'
    | '/houses/$id'
    | '/houses/$id/expenses/new'
  id:
    | '__root__'
    | '/'
    | '/agreement'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/auth/callback'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/houses/create'
    | '/invitations/accept'
    | '/payment/cancel'
    | '/payment/success'
    | '/houses/$id/invite'
    | '/houses/$id/'
    | '/houses/$id/expenses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgreementRoute: typeof AgreementRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  HousesCreateRoute: typeof HousesCreateRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  HousesIdInviteRoute: typeof HousesIdInviteRoute
  HousesIdIndexRoute: typeof HousesIdIndexRoute
  HousesIdExpensesNewRoute: typeof HousesIdExpensesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/create': {
      id: '/houses/create'
      path: '/houses/create'
      fullPath: '/houses/create'
      preLoaderRoute: typeof HousesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/$id/': {
      id: '/houses/$id/'
      path: '/houses/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof HousesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/$id/invite': {
      id: '/houses/$id/invite'
      path: '/houses/$id/invite'
      fullPath: '/houses/$id/invite'
      preLoaderRoute: typeof HousesIdInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/$id/expenses/new': {
      id: '/houses/$id/expenses/new'
      path: '/houses/$id/expenses/new'
      fullPath: '/houses/$id/expenses/new'
      preLoaderRoute: typeof HousesIdExpensesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgreementRoute: AgreementRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  HousesCreateRoute: HousesCreateRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  HousesIdInviteRoute: HousesIdInviteRoute,
  HousesIdIndexRoute: HousesIdIndexRoute,
  HousesIdExpensesNewRoute: HousesIdExpensesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
